<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ar.Auth.OpenId\Ar.Auth.OpenId.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Ar.Auth.OpenId.AspNetCore</PackageId>
    <Description>ASP.NET Core JWT Bearer authentication integration for Atlas Rig Auth.</Description>
  </PropertyGroup>

</Project>
