name: Deploy Backend to Azure Functions

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'ar-auth-api'
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: 'backend'
  FRONTEND_PATH: 'frontend'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Install Frontend Dependencies'
        run: |
          cd ${{ env.FRONTEND_PATH }}
          npm.cmd install

      - name: 'Build Frontend'
        run: |
          cd ${{ env.FRONTEND_PATH }}
          npm.cmd run build

      - name: 'Copy Frontend to Backend'
        run: |
          mkdir backend\wwwroot -Force
          xcopy /E /I /Y frontend\dist\* backend\wwwroot\

      - name: Setup DotNet ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore Dependencies'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build Project'
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

      - name: 'Publish Project'
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ./publish

      - name: Login to Azure
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_95EA35FAE7CB4F2985657FDFDAB866E0 }}
              tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F1EC04C0A004072B025788425900D7F }}
              subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AF4187BD34BE4D3387FA06733C036584 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'ar-auth'
          slot-name: 'Production'
          package: ./publish
          