# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - ar-auth

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend' # set this to the path to your web app project, defaults to the repository root
  FRONTEND_PATH: "frontend"
  DOTNET_VERSION: '9.0.x' # set this to the dotnet version to use

jobs:
  build:
    runs-on: ubuntu-latest
    environment: AZURE

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 'Install Frontend Dependencies'
        run: |
          cd ${{ env.FRONTEND_PATH }}
          npm install

      - name: 'Build Frontend'
        run: |
          cd ${{ env.FRONTEND_PATH }}
          npm run build

      - name: Substitute JSON 
        uses: restackio/update-json-file-action@2.1
        with:
          file:  ${{ env.FRONTEND_PATH }}/dist/config.json
          fields: '{"redirectUri":"${{ vars.REDIRECT_URI }}", "authUrl":"${{ vars.AUTH_API }}"}'
          

      - name: Move/Rename config.json to js
        run: |
              echo window.webConfig= > config.js
              cat config.json >> config.js
        working-directory:  ${{ env.FRONTEND_PATH }}/dist

        
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Copy Frontend to Backend'
        run: |
          mkdir -p backend/output/wwwroot
          cp -r frontend/dist/* './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/wwwroot'       
      
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_95EA35FAE7CB4F2985657FDFDAB866E0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F1EC04C0A004072B025788425900D7F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AF4187BD34BE4D3387FA06733C036584 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'ar-auth'
          slot-name: 'Production'
          package: './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'          
